package com.lucaf.robotic_core.UI;

import com.ghgande.j2mod.modbus.facade.ModbusSerialMaster;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import com.lucaf.robotic_core.SerialParams;
import com.lucaf.robotic_core.dataInterfaces.modbus.ModBusSerialCache;
import com.lucaf.robotic_core.dataInterfaces.modbus.ModbusRS485;
import com.lucaf.robotic_core.stepperOnline.iDmRs.IDMRS;
import com.lucaf.robotic_core.stepperOnline.iDmRs.ui.IDMRSUI;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.util.Locale;
import java.util.concurrent.CountDownLatch;

public class MainTuner {
    final JFrame frame = new JFrame("Select Tuner");

    private JPanel mainView;
    private JButton idmrs;

    ModbusRS485 createModbusRS485Connection(SerialParams params) {
        try {
            ModbusSerialMaster master = ModBusSerialCache.getModBusMasterCom(params);
            return new ModbusRS485(master, params.getUnitId(), "IDM-RS");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Failed to connect to ModBus RS485: " + e.getMessage(), "Connection Error", JOptionPane.ERROR_MESSAGE);
            return null;
        }
    }

    public MainTuner() {
        idmrs.addActionListener(e -> {
            ConnectionModal connectionModal = new ConnectionModal(params -> {
                if (params == null) return;
                ModbusRS485 modbusRS485 = createModbusRS485Connection(params);
                IDMRS motor = new IDMRS(modbusRS485);
                try {
                    IDMRSUI ui = new IDMRSUI(motor);
                    ui.createWindow();
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Failed to initialize IDM-RS UI: " + ex.getMessage(), "Initialization Error", JOptionPane.ERROR_MESSAGE);
                }
            });
            connectionModal.createWindow();
        });
    }

    /**
     * Create the connection modal window
     */
    public void createWindow() {
        frame.setContentPane(mainView);
        frame.pack();
        frame.setSize(200, 500);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);
    }

    public static void main(String[] args) {
        ThemeSetup.setupTheme();
        MainTuner tuner = new MainTuner();
        tuner.createWindow();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainView = new JPanel();
        mainView.setLayout(new GridLayoutManager(2, 1, new Insets(10, 10, 10, 10), -1, -1));
        idmrs = new JButton();
        Font idmrsFont = this.$$$getFont$$$(null, -1, 20, idmrs.getFont());
        if (idmrsFont != null) idmrs.setFont(idmrsFont);
        idmrs.setText("IDM-RS Tuner");
        mainView.add(idmrs, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        mainView.add(spacer1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainView;
    }

}
