/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.nanotec.nanolib;

public class BusHwOptionsDefault {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BusHwOptionsDefault(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BusHwOptionsDefault obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(BusHwOptionsDefault obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NanolibJNI.delete_BusHwOptionsDefault(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CanBus getCanBus() {
    long cPtr = NanolibJNI.BusHwOptionsDefault_canBus_get(swigCPtr, this);
    return (cPtr == 0) ? null : new CanBus(cPtr, false);
  }

  public Serial getSerial() {
    long cPtr = NanolibJNI.BusHwOptionsDefault_serial_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Serial(cPtr, false);
  }

  public RESTfulBus getRestfulBus() {
    long cPtr = NanolibJNI.BusHwOptionsDefault_restfulBus_get(swigCPtr, this);
    return (cPtr == 0) ? null : new RESTfulBus(cPtr, false);
  }

  public EtherCATBus getEthercatBus() {
    long cPtr = NanolibJNI.BusHwOptionsDefault_ethercatBus_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EtherCATBus(cPtr, false);
  }

  public BusHwOptionsDefault() {
    this(NanolibJNI.new_BusHwOptionsDefault(), true);
  }

}
