/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.nanotec.nanolib;

public final class BusScanInfo {
  public final static BusScanInfo Start = new BusScanInfo("Start");
  public final static BusScanInfo Progress = new BusScanInfo("Progress");
  public final static BusScanInfo FoundDevice = new BusScanInfo("FoundDevice");
  public final static BusScanInfo Finished = new BusScanInfo("Finished");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static BusScanInfo swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + BusScanInfo.class + " with value " + swigValue);
  }

  private BusScanInfo(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private BusScanInfo(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private BusScanInfo(String swigName, BusScanInfo swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static BusScanInfo[] swigValues = { Start, Progress, FoundDevice, Finished };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

