/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.nanotec.nanolib;

public class CanOpenNmtService {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CanOpenNmtService(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CanOpenNmtService obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(CanOpenNmtService obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NanolibJNI.delete_CanOpenNmtService(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public String getSTART() {
    return NanolibJNI.CanOpenNmtService_START_get(swigCPtr, this);
  }

  public String getSTOP() {
    return NanolibJNI.CanOpenNmtService_STOP_get(swigCPtr, this);
  }

  public String getPRE_OPERATIONAL() {
    return NanolibJNI.CanOpenNmtService_PRE_OPERATIONAL_get(swigCPtr, this);
  }

  public String getRESET() {
    return NanolibJNI.CanOpenNmtService_RESET_get(swigCPtr, this);
  }

  public String getRESET_COMMUNICATION() {
    return NanolibJNI.CanOpenNmtService_RESET_COMMUNICATION_get(swigCPtr, this);
  }

  public CanOpenNmtService() {
    this(NanolibJNI.new_CanOpenNmtService(), true);
  }

}
