/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.nanotec.nanolib;

public final class DataTransferInfo {
  public final static DataTransferInfo FileOpen = new DataTransferInfo("FileOpen");
  public final static DataTransferInfo Init = new DataTransferInfo("Init");
  public final static DataTransferInfo Progress = new DataTransferInfo("Progress");
  public final static DataTransferInfo Reboot = new DataTransferInfo("Reboot");
  public final static DataTransferInfo Finished = new DataTransferInfo("Finished");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static DataTransferInfo swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + DataTransferInfo.class + " with value " + swigValue);
  }

  private DataTransferInfo(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private DataTransferInfo(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private DataTransferInfo(String swigName, DataTransferInfo swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static DataTransferInfo[] swigValues = { FileOpen, Init, Progress, Reboot, Finished };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

