/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.nanotec.nanolib;

public class DeviceHandle {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DeviceHandle(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DeviceHandle obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(DeviceHandle obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NanolibJNI.delete_DeviceHandle(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DeviceHandle() {
    this(NanolibJNI.new_DeviceHandle(), true);
  }

  public boolean equals(DeviceHandle other) {
    return NanolibJNI.DeviceHandle_equals(swigCPtr, this, DeviceHandle.getCPtr(other), other);
  }

  public String toString() {
    return NanolibJNI.DeviceHandle_toString(swigCPtr, this);
  }

}
