/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.nanotec.nanolib;

public final class DeviceConnectionStateInfo {
  public final static DeviceConnectionStateInfo Disconnected = new DeviceConnectionStateInfo("Disconnected");
  public final static DeviceConnectionStateInfo Connected = new DeviceConnectionStateInfo("Connected");
  public final static DeviceConnectionStateInfo ConnectedBootloader = new DeviceConnectionStateInfo("ConnectedBootloader");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static DeviceConnectionStateInfo swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + DeviceConnectionStateInfo.class + " with value " + swigValue);
  }

  private DeviceConnectionStateInfo(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private DeviceConnectionStateInfo(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private DeviceConnectionStateInfo(String swigName, DeviceConnectionStateInfo swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static DeviceConnectionStateInfo[] swigValues = { Disconnected, Connected, ConnectedBootloader };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

