/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.nanotec.nanolib;

public class EtherCATState {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EtherCATState(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EtherCATState obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(EtherCATState obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NanolibJNI.delete_EtherCATState(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public String getNONE() {
    return NanolibJNI.EtherCATState_NONE_get(swigCPtr, this);
  }

  public String getINIT() {
    return NanolibJNI.EtherCATState_INIT_get(swigCPtr, this);
  }

  public String getPRE_OPERATIONAL() {
    return NanolibJNI.EtherCATState_PRE_OPERATIONAL_get(swigCPtr, this);
  }

  public String getBOOT() {
    return NanolibJNI.EtherCATState_BOOT_get(swigCPtr, this);
  }

  public String getSAFE_OPERATIONAL() {
    return NanolibJNI.EtherCATState_SAFE_OPERATIONAL_get(swigCPtr, this);
  }

  public String getOPERATIONAL() {
    return NanolibJNI.EtherCATState_OPERATIONAL_get(swigCPtr, this);
  }

  public EtherCATState() {
    this(NanolibJNI.new_EtherCATState(), true);
  }

}
