/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.nanotec.nanolib;

public class imaxdiv_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected imaxdiv_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(imaxdiv_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(imaxdiv_t obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NanolibJNI.delete_imaxdiv_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setQuot(long value) {
    NanolibJNI.imaxdiv_t_quot_set(swigCPtr, this, value);
  }

  public long getQuot() {
    return NanolibJNI.imaxdiv_t_quot_get(swigCPtr, this);
  }

  public void setRem(long value) {
    NanolibJNI.imaxdiv_t_rem_set(swigCPtr, this, value);
  }

  public long getRem() {
    return NanolibJNI.imaxdiv_t_rem_get(swigCPtr, this);
  }

  public imaxdiv_t() {
    this(NanolibJNI.new_imaxdiv_t(), true);
  }

}
