/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.nanotec.nanolib;

public final class LogModule {
  public final static LogModule NanolibCore = new LogModule("NanolibCore", NanolibJNI.LogModule_NanolibCore_get());
  public final static LogModule NanolibCANopen = new LogModule("NanolibCANopen");
  public final static LogModule NanolibModbus = new LogModule("NanolibModbus");
  public final static LogModule NanolibEtherCAT = new LogModule("NanolibEtherCAT");
  public final static LogModule NanolibRest = new LogModule("NanolibRest");
  public final static LogModule NanolibUSB = new LogModule("NanolibUSB");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static LogModule swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + LogModule.class + " with value " + swigValue);
  }

  private LogModule(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private LogModule(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private LogModule(String swigName, LogModule swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static LogModule[] swigValues = { NanolibCore, NanolibCANopen, NanolibModbus, NanolibEtherCAT, NanolibRest, NanolibUSB };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

