/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.nanotec.nanolib;

public interface NanolibConstants {
  public final static int LOG_LEVEL_TRACE = NanolibJNI.LOG_LEVEL_TRACE_get();
  public final static int LOG_LEVEL_DEBUG = NanolibJNI.LOG_LEVEL_DEBUG_get();
  public final static int LOG_LEVEL_INFO = NanolibJNI.LOG_LEVEL_INFO_get();
  public final static int LOG_LEVEL_WARN = NanolibJNI.LOG_LEVEL_WARN_get();
  public final static int LOG_LEVEL_ERROR = NanolibJNI.LOG_LEVEL_ERROR_get();
  public final static int LOG_LEVEL_CRITICAL = NanolibJNI.LOG_LEVEL_CRITICAL_get();
  public final static int LOG_LEVEL_OFF = NanolibJNI.LOG_LEVEL_OFF_get();
}
