/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.nanotec.nanolib;

public class ObjectEntry {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ObjectEntry(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ObjectEntry obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(ObjectEntry obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NanolibJNI.delete_ObjectEntry(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ObjectEntry() {
    this(NanolibJNI.new_ObjectEntry(), true);
  }

  public String getName() {
    return NanolibJNI.ObjectEntry_getName(swigCPtr, this);
  }

  public boolean getPrivate() {
    return NanolibJNI.ObjectEntry_getPrivate(swigCPtr, this);
  }

  public int getIndex() {
    return NanolibJNI.ObjectEntry_getIndex(swigCPtr, this);
  }

  public ObjectEntryDataType getDataType() {
    return ObjectEntryDataType.swigToEnum(NanolibJNI.ObjectEntry_getDataType(swigCPtr, this));
  }

  public ObjectCode getObjectCode() {
    return ObjectCode.swigToEnum(NanolibJNI.ObjectEntry_getObjectCode(swigCPtr, this));
  }

  public ObjectSaveable getObjectSaveable() {
    return ObjectSaveable.swigToEnum(NanolibJNI.ObjectEntry_getObjectSaveable(swigCPtr, this));
  }

  public short getMaxSubIndex() {
    return NanolibJNI.ObjectEntry_getMaxSubIndex(swigCPtr, this);
  }

  public ObjectSubEntry getSubEntry(short subIndex) {
    return new ObjectSubEntry(NanolibJNI.ObjectEntry_getSubEntry(swigCPtr, this, subIndex), false);
  }

}
