/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.nanotec.nanolib;

public final class ObjectSaveable {
  public final static ObjectSaveable APPLICATION = new ObjectSaveable("APPLICATION");
  public final static ObjectSaveable COMMUNICATION = new ObjectSaveable("COMMUNICATION");
  public final static ObjectSaveable DRIVE = new ObjectSaveable("DRIVE");
  public final static ObjectSaveable MISC_CONFIG = new ObjectSaveable("MISC_CONFIG");
  public final static ObjectSaveable MODBUS_RTU = new ObjectSaveable("MODBUS_RTU");
  public final static ObjectSaveable NO = new ObjectSaveable("NO");
  public final static ObjectSaveable TUNING = new ObjectSaveable("TUNING");
  public final static ObjectSaveable CUSTOMER = new ObjectSaveable("CUSTOMER");
  public final static ObjectSaveable ETHERNET = new ObjectSaveable("ETHERNET");
  public final static ObjectSaveable CANOPEN = new ObjectSaveable("CANOPEN");
  public final static ObjectSaveable PROFIBUS = new ObjectSaveable("PROFIBUS");
  public final static ObjectSaveable VERIFY1020 = new ObjectSaveable("VERIFY1020");
  public final static ObjectSaveable UNKNOWN_SAVEABLE_TYPE = new ObjectSaveable("UNKNOWN_SAVEABLE_TYPE");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ObjectSaveable swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ObjectSaveable.class + " with value " + swigValue);
  }

  private ObjectSaveable(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ObjectSaveable(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ObjectSaveable(String swigName, ObjectSaveable swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ObjectSaveable[] swigValues = { APPLICATION, COMMUNICATION, DRIVE, MISC_CONFIG, MODBUS_RTU, NO, TUNING, CUSTOMER, ETHERNET, CANOPEN, PROFIBUS, VERIFY1020, UNKNOWN_SAVEABLE_TYPE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

