/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.nanotec.nanolib;

public final class ObjectModificationAttribute {
  public final static ObjectModificationAttribute Constant = new ObjectModificationAttribute("Constant");
  public final static ObjectModificationAttribute Variable = new ObjectModificationAttribute("Variable");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ObjectModificationAttribute swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ObjectModificationAttribute.class + " with value " + swigValue);
  }

  private ObjectModificationAttribute(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ObjectModificationAttribute(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ObjectModificationAttribute(String swigName, ObjectModificationAttribute swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ObjectModificationAttribute[] swigValues = { Constant, Variable };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

