/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.nanotec.nanolib;

public final class ObjectCode {
  public final static ObjectCode Null = new ObjectCode("Null", NanolibJNI.ObjectCode_Null_get());
  public final static ObjectCode Deftype = new ObjectCode("Deftype", NanolibJNI.ObjectCode_Deftype_get());
  public final static ObjectCode Defstruct = new ObjectCode("Defstruct", NanolibJNI.ObjectCode_Defstruct_get());
  public final static ObjectCode Var = new ObjectCode("Var", NanolibJNI.ObjectCode_Var_get());
  public final static ObjectCode Array = new ObjectCode("Array", NanolibJNI.ObjectCode_Array_get());
  public final static ObjectCode Record = new ObjectCode("Record", NanolibJNI.ObjectCode_Record_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ObjectCode swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ObjectCode.class + " with value " + swigValue);
  }

  private ObjectCode(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ObjectCode(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ObjectCode(String swigName, ObjectCode swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ObjectCode[] swigValues = { Null, Deftype, Defstruct, Var, Array, Record };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

