/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.nanotec.nanolib;

public final class ObjectEntryDataType {
  public final static ObjectEntryDataType Invalid = new ObjectEntryDataType("Invalid", NanolibJNI.ObjectEntryDataType_Invalid_get());
  public final static ObjectEntryDataType Boolean = new ObjectEntryDataType("Boolean", NanolibJNI.ObjectEntryDataType_Boolean_get());
  public final static ObjectEntryDataType Integer8 = new ObjectEntryDataType("Integer8", NanolibJNI.ObjectEntryDataType_Integer8_get());
  public final static ObjectEntryDataType Integer16 = new ObjectEntryDataType("Integer16", NanolibJNI.ObjectEntryDataType_Integer16_get());
  public final static ObjectEntryDataType Integer32 = new ObjectEntryDataType("Integer32", NanolibJNI.ObjectEntryDataType_Integer32_get());
  public final static ObjectEntryDataType Unsigned8 = new ObjectEntryDataType("Unsigned8", NanolibJNI.ObjectEntryDataType_Unsigned8_get());
  public final static ObjectEntryDataType Unsigned16 = new ObjectEntryDataType("Unsigned16", NanolibJNI.ObjectEntryDataType_Unsigned16_get());
  public final static ObjectEntryDataType Unsigned32 = new ObjectEntryDataType("Unsigned32", NanolibJNI.ObjectEntryDataType_Unsigned32_get());
  public final static ObjectEntryDataType Real32 = new ObjectEntryDataType("Real32", NanolibJNI.ObjectEntryDataType_Real32_get());
  public final static ObjectEntryDataType VisibleString = new ObjectEntryDataType("VisibleString", NanolibJNI.ObjectEntryDataType_VisibleString_get());
  public final static ObjectEntryDataType OctetString = new ObjectEntryDataType("OctetString", NanolibJNI.ObjectEntryDataType_OctetString_get());
  public final static ObjectEntryDataType UnicodeString = new ObjectEntryDataType("UnicodeString", NanolibJNI.ObjectEntryDataType_UnicodeString_get());
  public final static ObjectEntryDataType TimeOfDay = new ObjectEntryDataType("TimeOfDay", NanolibJNI.ObjectEntryDataType_TimeOfDay_get());
  public final static ObjectEntryDataType TimeDifference = new ObjectEntryDataType("TimeDifference", NanolibJNI.ObjectEntryDataType_TimeDifference_get());
  public final static ObjectEntryDataType Domain = new ObjectEntryDataType("Domain", NanolibJNI.ObjectEntryDataType_Domain_get());
  public final static ObjectEntryDataType Integer24 = new ObjectEntryDataType("Integer24", NanolibJNI.ObjectEntryDataType_Integer24_get());
  public final static ObjectEntryDataType Real64 = new ObjectEntryDataType("Real64", NanolibJNI.ObjectEntryDataType_Real64_get());
  public final static ObjectEntryDataType Integer40 = new ObjectEntryDataType("Integer40", NanolibJNI.ObjectEntryDataType_Integer40_get());
  public final static ObjectEntryDataType Integer48 = new ObjectEntryDataType("Integer48", NanolibJNI.ObjectEntryDataType_Integer48_get());
  public final static ObjectEntryDataType Integer56 = new ObjectEntryDataType("Integer56", NanolibJNI.ObjectEntryDataType_Integer56_get());
  public final static ObjectEntryDataType Integer64 = new ObjectEntryDataType("Integer64", NanolibJNI.ObjectEntryDataType_Integer64_get());
  public final static ObjectEntryDataType Unsigned24 = new ObjectEntryDataType("Unsigned24", NanolibJNI.ObjectEntryDataType_Unsigned24_get());
  public final static ObjectEntryDataType Unsigned40 = new ObjectEntryDataType("Unsigned40", NanolibJNI.ObjectEntryDataType_Unsigned40_get());
  public final static ObjectEntryDataType Unsigned48 = new ObjectEntryDataType("Unsigned48", NanolibJNI.ObjectEntryDataType_Unsigned48_get());
  public final static ObjectEntryDataType Unsigned56 = new ObjectEntryDataType("Unsigned56", NanolibJNI.ObjectEntryDataType_Unsigned56_get());
  public final static ObjectEntryDataType Unsigned64 = new ObjectEntryDataType("Unsigned64", NanolibJNI.ObjectEntryDataType_Unsigned64_get());
  public final static ObjectEntryDataType PdoCommunicationParameter = new ObjectEntryDataType("PdoCommunicationParameter", NanolibJNI.ObjectEntryDataType_PdoCommunicationParameter_get());
  public final static ObjectEntryDataType PdoMapping = new ObjectEntryDataType("PdoMapping", NanolibJNI.ObjectEntryDataType_PdoMapping_get());
  public final static ObjectEntryDataType Identity = new ObjectEntryDataType("Identity", NanolibJNI.ObjectEntryDataType_Identity_get());
  public final static ObjectEntryDataType SyncmgrSynchronization = new ObjectEntryDataType("SyncmgrSynchronization", NanolibJNI.ObjectEntryDataType_SyncmgrSynchronization_get());
  public final static ObjectEntryDataType UserStorageArea = new ObjectEntryDataType("UserStorageArea", NanolibJNI.ObjectEntryDataType_UserStorageArea_get());
  public final static ObjectEntryDataType SamplerConfig = new ObjectEntryDataType("SamplerConfig", NanolibJNI.ObjectEntryDataType_SamplerConfig_get());
  public final static ObjectEntryDataType SamplerTimebase = new ObjectEntryDataType("SamplerTimebase", NanolibJNI.ObjectEntryDataType_SamplerTimebase_get());
  public final static ObjectEntryDataType PdiInput = new ObjectEntryDataType("PdiInput", NanolibJNI.ObjectEntryDataType_PdiInput_get());
  public final static ObjectEntryDataType PdiOutput = new ObjectEntryDataType("PdiOutput", NanolibJNI.ObjectEntryDataType_PdiOutput_get());
  public final static ObjectEntryDataType ClosedLoopControllerParameter = new ObjectEntryDataType("ClosedLoopControllerParameter", NanolibJNI.ObjectEntryDataType_ClosedLoopControllerParameter_get());
  public final static ObjectEntryDataType OpenLoopControllerParameter = new ObjectEntryDataType("OpenLoopControllerParameter", NanolibJNI.ObjectEntryDataType_OpenLoopControllerParameter_get());
  public final static ObjectEntryDataType SsiEncoder = new ObjectEntryDataType("SsiEncoder", NanolibJNI.ObjectEntryDataType_SsiEncoder_get());
  public final static ObjectEntryDataType N2 = new ObjectEntryDataType("N2", NanolibJNI.ObjectEntryDataType_N2_get());
  public final static ObjectEntryDataType N4 = new ObjectEntryDataType("N4", NanolibJNI.ObjectEntryDataType_N4_get());
  public final static ObjectEntryDataType V2 = new ObjectEntryDataType("V2", NanolibJNI.ObjectEntryDataType_V2_get());
  public final static ObjectEntryDataType X2 = new ObjectEntryDataType("X2", NanolibJNI.ObjectEntryDataType_X2_get());
  public final static ObjectEntryDataType X4 = new ObjectEntryDataType("X4", NanolibJNI.ObjectEntryDataType_X4_get());
  public final static ObjectEntryDataType InterpolationTimePeriod = new ObjectEntryDataType("InterpolationTimePeriod", NanolibJNI.ObjectEntryDataType_InterpolationTimePeriod_get());
  public final static ObjectEntryDataType InterpolationDataConfiguration = new ObjectEntryDataType("InterpolationDataConfiguration", NanolibJNI.ObjectEntryDataType_InterpolationDataConfiguration_get());
  public final static ObjectEntryDataType VelocityAccelerationDeceleration = new ObjectEntryDataType("VelocityAccelerationDeceleration", NanolibJNI.ObjectEntryDataType_VelocityAccelerationDeceleration_get());
  public final static ObjectEntryDataType Simple = new ObjectEntryDataType("Simple", NanolibJNI.ObjectEntryDataType_Simple_get());
  public final static ObjectEntryDataType Complex = new ObjectEntryDataType("Complex", NanolibJNI.ObjectEntryDataType_Complex_get());
  public final static ObjectEntryDataType Unknown = new ObjectEntryDataType("Unknown", NanolibJNI.ObjectEntryDataType_Unknown_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ObjectEntryDataType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ObjectEntryDataType.class + " with value " + swigValue);
  }

  private ObjectEntryDataType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ObjectEntryDataType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ObjectEntryDataType(String swigName, ObjectEntryDataType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ObjectEntryDataType[] swigValues = { Invalid, Boolean, Integer8, Integer16, Integer32, Unsigned8, Unsigned16, Unsigned32, Real32, VisibleString, OctetString, UnicodeString, TimeOfDay, TimeDifference, Domain, Integer24, Real64, Integer40, Integer48, Integer56, Integer64, Unsigned24, Unsigned40, Unsigned48, Unsigned56, Unsigned64, PdoCommunicationParameter, PdoMapping, Identity, SyncmgrSynchronization, UserStorageArea, SamplerConfig, SamplerTimebase, PdiInput, PdiOutput, ClosedLoopControllerParameter, OpenLoopControllerParameter, SsiEncoder, N2, N4, V2, X2, X4, InterpolationTimePeriod, InterpolationDataConfiguration, VelocityAccelerationDeceleration, Simple, Complex, Unknown };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

