/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.nanotec.nanolib;

public final class ObjectPdoAccessAttribute {
  public final static ObjectPdoAccessAttribute Tx = new ObjectPdoAccessAttribute("Tx", NanolibJNI.ObjectPdoAccessAttribute_Tx_get());
  public final static ObjectPdoAccessAttribute Rx = new ObjectPdoAccessAttribute("Rx", NanolibJNI.ObjectPdoAccessAttribute_Rx_get());
  public final static ObjectPdoAccessAttribute TxRx = new ObjectPdoAccessAttribute("TxRx", NanolibJNI.ObjectPdoAccessAttribute_TxRx_get());
  public final static ObjectPdoAccessAttribute No = new ObjectPdoAccessAttribute("No", NanolibJNI.ObjectPdoAccessAttribute_No_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ObjectPdoAccessAttribute swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ObjectPdoAccessAttribute.class + " with value " + swigValue);
  }

  private ObjectPdoAccessAttribute(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ObjectPdoAccessAttribute(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ObjectPdoAccessAttribute(String swigName, ObjectPdoAccessAttribute swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ObjectPdoAccessAttribute[] swigValues = { Tx, Rx, TxRx, No };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

