/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.nanotec.nanolib;

public final class ObjectSdoAccessAttribute {
  public final static ObjectSdoAccessAttribute ReadOnly = new ObjectSdoAccessAttribute("ReadOnly", NanolibJNI.ObjectSdoAccessAttribute_ReadOnly_get());
  public final static ObjectSdoAccessAttribute WriteOnly = new ObjectSdoAccessAttribute("WriteOnly", NanolibJNI.ObjectSdoAccessAttribute_WriteOnly_get());
  public final static ObjectSdoAccessAttribute ReadWrite = new ObjectSdoAccessAttribute("ReadWrite", NanolibJNI.ObjectSdoAccessAttribute_ReadWrite_get());
  public final static ObjectSdoAccessAttribute NoAccess = new ObjectSdoAccessAttribute("NoAccess", NanolibJNI.ObjectSdoAccessAttribute_NoAccess_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ObjectSdoAccessAttribute swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ObjectSdoAccessAttribute.class + " with value " + swigValue);
  }

  private ObjectSdoAccessAttribute(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ObjectSdoAccessAttribute(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ObjectSdoAccessAttribute(String swigName, ObjectSdoAccessAttribute swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ObjectSdoAccessAttribute[] swigValues = { ReadOnly, WriteOnly, ReadWrite, NoAccess };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

