/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.nanotec.nanolib;

public class OdLibrary {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OdLibrary(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OdLibrary obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(OdLibrary obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NanolibJNI.delete_OdLibrary(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public long getObjectDictionaryCount() {
    return NanolibJNI.OdLibrary_getObjectDictionaryCount(swigCPtr, this);
  }

  public ResultObjectDictionary getObjectDictionary(long odIndex) {
    return new ResultObjectDictionary(NanolibJNI.OdLibrary_getObjectDictionary(swigCPtr, this, odIndex), true);
  }

  public ResultObjectDictionary addObjectDictionaryFromFile(String absoluteXmlFilePath) {
    return new ResultObjectDictionary(NanolibJNI.OdLibrary_addObjectDictionaryFromFile(swigCPtr, this, absoluteXmlFilePath), true);
  }

  public ResultObjectDictionary addObjectDictionary(ByteVector odXmlData, String xmlFilePath) {
    return new ResultObjectDictionary(NanolibJNI.OdLibrary_addObjectDictionary__SWIG_0(swigCPtr, this, ByteVector.getCPtr(odXmlData), odXmlData, xmlFilePath), true);
  }

  public ResultObjectDictionary addObjectDictionary(ByteVector odXmlData) {
    return new ResultObjectDictionary(NanolibJNI.OdLibrary_addObjectDictionary__SWIG_1(swigCPtr, this, ByteVector.getCPtr(odXmlData), odXmlData), true);
  }

}
