/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.nanotec.nanolib;

public class Peak {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Peak(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Peak obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(Peak obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NanolibJNI.delete_Peak(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public String getADAPTER_BUS_NUMBER_OPTIONS_NAME() {
    return NanolibJNI.Peak_ADAPTER_BUS_NUMBER_OPTIONS_NAME_get(swigCPtr, this);
  }

  public PeakAdapterBusNumber getAdapterBusNumber() {
    long cPtr = NanolibJNI.Peak_adapterBusNumber_get(swigCPtr, this);
    return (cPtr == 0) ? null : new PeakAdapterBusNumber(cPtr, false);
  }

  public Peak() {
    this(NanolibJNI.new_Peak(), true);
  }

}
