/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.nanotec.nanolib;

public class RESTfulBus {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RESTfulBus(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RESTfulBus obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(RESTfulBus obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NanolibJNI.delete_RESTfulBus(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public String getCONNECT_TIMEOUT_OPTION_NAME() {
    return NanolibJNI.RESTfulBus_CONNECT_TIMEOUT_OPTION_NAME_get(swigCPtr, this);
  }

  public long getDEFAULT_CONNECT_TIMEOUT() {
    return NanolibJNI.RESTfulBus_DEFAULT_CONNECT_TIMEOUT_get(swigCPtr, this);
  }

  public String getREQUEST_TIMEOUT_OPTION_NAME() {
    return NanolibJNI.RESTfulBus_REQUEST_TIMEOUT_OPTION_NAME_get(swigCPtr, this);
  }

  public long getDEFAULT_REQUEST_TIMEOUT() {
    return NanolibJNI.RESTfulBus_DEFAULT_REQUEST_TIMEOUT_get(swigCPtr, this);
  }

  public String getRESPONSE_TIMEOUT_OPTION_NAME() {
    return NanolibJNI.RESTfulBus_RESPONSE_TIMEOUT_OPTION_NAME_get(swigCPtr, this);
  }

  public long getDEFAULT_RESPONSE_TIMEOUT() {
    return NanolibJNI.RESTfulBus_DEFAULT_RESPONSE_TIMEOUT_get(swigCPtr, this);
  }

  public RESTfulBus() {
    this(NanolibJNI.new_RESTfulBus(), true);
  }

}
