/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.nanotec.nanolib;

public class ResultConnectionState extends Result {
  private transient long swigCPtr;

  protected ResultConnectionState(long cPtr, boolean cMemoryOwn) {
    super(NanolibJNI.ResultConnectionState_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ResultConnectionState obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(ResultConnectionState obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NanolibJNI.delete_ResultConnectionState(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ResultConnectionState(DeviceConnectionStateInfo result_) {
    this(NanolibJNI.new_ResultConnectionState__SWIG_0(result_.swigValue()), true);
  }

  public ResultConnectionState(String errorString_) {
    this(NanolibJNI.new_ResultConnectionState__SWIG_1(errorString_), true);
  }

  public ResultConnectionState(NlcErrorCode errCode, String errorString_) {
    this(NanolibJNI.new_ResultConnectionState__SWIG_2(errCode.swigValue(), errorString_), true);
  }

  public ResultConnectionState(NlcErrorCode errCode, long exErrCode, String errorString_) {
    this(NanolibJNI.new_ResultConnectionState__SWIG_3(errCode.swigValue(), exErrCode, errorString_), true);
  }

  public ResultConnectionState(Result result) {
    this(NanolibJNI.new_ResultConnectionState__SWIG_4(Result.getCPtr(result), result), true);
  }

  public DeviceConnectionStateInfo getResult() {
    return DeviceConnectionStateInfo.swigToEnum(NanolibJNI.ResultConnectionState_getResult(swigCPtr, this));
  }

}
