/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.nanotec.nanolib;

public final class SamplerState {
  public final static SamplerState Unconfigured = new SamplerState("Unconfigured");
  public final static SamplerState Configured = new SamplerState("Configured");
  public final static SamplerState Ready = new SamplerState("Ready");
  public final static SamplerState Running = new SamplerState("Running");
  public final static SamplerState Completed = new SamplerState("Completed");
  public final static SamplerState Failed = new SamplerState("Failed");
  public final static SamplerState Cancelled = new SamplerState("Cancelled");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SamplerState swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SamplerState.class + " with value " + swigValue);
  }

  private SamplerState(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SamplerState(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SamplerState(String swigName, SamplerState swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SamplerState[] swigValues = { Unconfigured, Configured, Ready, Running, Completed, Failed, Cancelled };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

