/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.nanotec.nanolib;

public class SamplerNotify {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SamplerNotify(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SamplerNotify obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(SamplerNotify obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NanolibJNI.delete_SamplerNotify(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    NanolibJNI.SamplerNotify_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    NanolibJNI.SamplerNotify_change_ownership(this, swigCPtr, true);
  }

  public void notify(ResultVoid lastError, SamplerState samplerState, SampleDataVector sampleDatas, long applicationData) {
    NanolibJNI.SamplerNotify_notify(swigCPtr, this, ResultVoid.getCPtr(lastError), lastError, samplerState.swigValue(), SampleDataVector.getCPtr(sampleDatas), sampleDatas, applicationData);
  }

  public SamplerNotify() {
    this(NanolibJNI.new_SamplerNotify(), true);
    NanolibJNI.SamplerNotify_director_connect(this, swigCPtr, true, true);
  }

}
