/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.nanotec.nanolib;

public final class SamplerMode {
  public final static SamplerMode Normal = new SamplerMode("Normal");
  public final static SamplerMode Repetitive = new SamplerMode("Repetitive");
  public final static SamplerMode Continuous = new SamplerMode("Continuous");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SamplerMode swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SamplerMode.class + " with value " + swigValue);
  }

  private SamplerMode(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SamplerMode(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SamplerMode(String swigName, SamplerMode swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SamplerMode[] swigValues = { Normal, Repetitive, Continuous };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

