/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.nanotec.nanolib;

public class SampledValue {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SampledValue(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SampledValue obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(SampledValue obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NanolibJNI.delete_SampledValue(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setValue(long value) {
    NanolibJNI.SampledValue_value_set(swigCPtr, this, value);
  }

  public long getValue() {
    return NanolibJNI.SampledValue_value_get(swigCPtr, this);
  }

  public void setCollectTimeMsec(java.math.BigInteger value) {
    NanolibJNI.SampledValue_collectTimeMsec_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getCollectTimeMsec() {
    return NanolibJNI.SampledValue_collectTimeMsec_get(swigCPtr, this);
  }

  public SampledValue() {
    this(NanolibJNI.new_SampledValue(), true);
  }

}
