/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.nanotec.nanolib;

public class Serial {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Serial(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Serial obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(Serial obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NanolibJNI.delete_Serial(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public String getBAUD_RATE_OPTIONS_NAME() {
    return NanolibJNI.Serial_BAUD_RATE_OPTIONS_NAME_get(swigCPtr, this);
  }

  public SerialBaudRate getBaudRate() {
    long cPtr = NanolibJNI.Serial_baudRate_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SerialBaudRate(cPtr, false);
  }

  public String getPARITY_OPTIONS_NAME() {
    return NanolibJNI.Serial_PARITY_OPTIONS_NAME_get(swigCPtr, this);
  }

  public SerialParity getParity() {
    long cPtr = NanolibJNI.Serial_parity_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SerialParity(cPtr, false);
  }

  public Serial() {
    this(NanolibJNI.new_Serial(), true);
  }

}
