/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.nanotec.nanolib;

public class SerialParity {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SerialParity(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SerialParity obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(SerialParity obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NanolibJNI.delete_SerialParity(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public String getNONE() {
    return NanolibJNI.SerialParity_NONE_get(swigCPtr, this);
  }

  public String getODD() {
    return NanolibJNI.SerialParity_ODD_get(swigCPtr, this);
  }

  public String getEVEN() {
    return NanolibJNI.SerialParity_EVEN_get(swigCPtr, this);
  }

  public String getMARK() {
    return NanolibJNI.SerialParity_MARK_get(swigCPtr, this);
  }

  public String getSPACE() {
    return NanolibJNI.SerialParity_SPACE_get(swigCPtr, this);
  }

  public SerialParity() {
    this(NanolibJNI.new_SerialParity(), true);
  }

}
